// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7umhZFArcnXl-BGIXq5aqLNMh9jF6ZMw',
    appId: '1:629301331458:web:b80b1ec707559b12a6091b',
    messagingSenderId: '629301331458',
    projectId: 'untitled1-ea672',
    authDomain: 'untitled1-ea672.firebaseapp.com',
    storageBucket: 'untitled1-ea672.appspot.com',
    measurementId: 'G-98GV0YSQ4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA33WCEoEiUxmI50xbaZH6kZ_tCcbQn_TE',
    appId: '1:629301331458:android:cdd0b78f84e81844a6091b',
    messagingSenderId: '629301331458',
    projectId: 'untitled1-ea672',
    storageBucket: 'untitled1-ea672.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBfFWLFhVmZfaBuPkqt87blZ7Y3P1gPTU',
    appId: '1:629301331458:ios:0e1015bd1887242fa6091b',
    messagingSenderId: '629301331458',
    projectId: 'untitled1-ea672',
    storageBucket: 'untitled1-ea672.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBfFWLFhVmZfaBuPkqt87blZ7Y3P1gPTU',
    appId: '1:629301331458:ios:0e1015bd1887242fa6091b',
    messagingSenderId: '629301331458',
    projectId: 'untitled1-ea672',
    storageBucket: 'untitled1-ea672.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7umhZFArcnXl-BGIXq5aqLNMh9jF6ZMw',
    appId: '1:629301331458:web:ba4f36aa7e5caac6a6091b',
    messagingSenderId: '629301331458',
    projectId: 'untitled1-ea672',
    authDomain: 'untitled1-ea672.firebaseapp.com',
    storageBucket: 'untitled1-ea672.appspot.com',
    measurementId: 'G-LH0DNDBJCN',
  );
}
